spring:
  application:
    name: national-hospital-singapore


  datasource:
    url: jdbc:h2:mem:national_hospital
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #consol select H2 DB Url
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          auth0:
            client-id: B8pMqzyoEbYkEwn76A3mZV5A5q1BHZ80
            client-secret: yKTU38lQ25Y_GK4cIaQxulsS9cyNrgd-F_DOm57as_GS1gTfoFfD5FqWfe8YaS-L
            scope:
              - openid
            redirect-uri: http://localhost:8080/login/oauth2/code/auth0
        provider:
          auth0:
            issuer-uri: https://rameshkp2.us.auth0.com/