stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
  SPRING_PROFILES_ACTIVE: "prod"

cache:
  paths:
    - .m2/repository

before_script:
  - export PATH=$JAVA_HOME/bin:$PATH

build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn test

package:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" > key.pem
    - chmod 600 key.pem
  script:
    - scp -i key.pem target/*.jar $USERNAME@$SERVER:/opt/apps/national-hospital-singapore-0.0.1-SNAPSHOT.jar
    - ssh -i key.pem $USERNAME@$SERVER 'systemctl restart national-hospital-singapore'
