name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run Tests
        run: mvn clean test

      - name: Build Project
        run: mvn clean package

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Deploy with SCP (example)
        env:
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem target/national-hospital-singapore.jar $USERNAME@$SERVER:/opt/apps/national-hospital-singapore.jar
          ssh -i key.pem $USERNAME@$SERVER "systemctl restart national-hospital-singapore"

